# See documentation: https://www.gitpod.io/docs/config-gitpod-file

---
tasks:
  - init: |
      curl -sL install.mob.sh | sudo sh
      cargo build

vscode:
  extensions:
    - matklad.rust-analyzer
